COMBO_ENABLE = yes
CONSOLE_ENABLE = yes
GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MUSIC_ENABLE = no
OLED_ENABLE = no
POINTING_DEVICE_ENABLE = no
# RGBLIGHT_ENABLE = yes
# RGB_MATRIX_ENABLE = no
# RGB_MATRIX_DRIVER = WS2812
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes

# userspace rules
ART_ENABLE = yes
CASE_MODES_ENABLE = yes
GAMING_ENABLE = yes
GIT_ENABLE = yes
INTROSPECTION_KEYMAP_C = combos.c
