CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
MUSIC_ENABLE = no
RGB_MATRIX_ENABLE = yes
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no

# userspace rules
ART_ENABLE = yes
