CONSOLE_ENABLE = yes
GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MUSIC_ENABLE = no
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes
REPEAT_KEY_ENABLE = yes

# userspace rules
ART_ENABLE = yes
# CASE_MODES_ENABLE = yes
GAMING_ENABLE = yes
GIT_ENABLE = yes
